version: "2.2"

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-server
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db