version: "2.2"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /mnt/c/Users/boban/documents/database:/tmp
  web:
    image: blog-web:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
